/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuditLogs {
  action: string | null;
  created_at: Generated<Timestamp | null>;
  details: Json | null;
  entity_id: string | null;
  entity_type: string | null;
  id: Generated<string>;
  ip_address: string | null;
  user_agent: string | null;
  user_id: string | null;
  workspace_id: string | null;
}

export interface ChannelMembers {
  channel_id: string | null;
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  is_muted: Generated<boolean | null>;
  joined_at: Timestamp | null;
  last_read_message_id: string | null;
  notifications_enabled: Generated<boolean | null>;
  role: string | null;
  updated_at: Generated<Timestamp | null>;
  user_id: string | null;
}

export interface Channels {
  created_at: Generated<Timestamp | null>;
  created_by: string | null;
  deleted_at: Timestamp | null;
  description: string | null;
  has_retention_policy: Generated<boolean | null>;
  icon_url: string | null;
  id: Generated<string>;
  is_direct: Generated<boolean | null>;
  is_group_dm: Generated<boolean | null>;
  is_private: Generated<boolean | null>;
  name: string;
  retention_days: number | null;
  slug: string | null;
  topic: string | null;
  updated_at: Generated<Timestamp | null>;
  workspace_id: string | null;
}

export interface CodeSnippets {
  channel_id: string | null;
  content: string | null;
  created_at: Generated<Timestamp | null>;
  deleted_at: Timestamp | null;
  document_id: string | null;
  id: Generated<string>;
  is_editable: Generated<boolean | null>;
  is_public: Generated<boolean | null>;
  language: string | null;
  message_id: string | null;
  title: string | null;
  updated_at: Generated<Timestamp | null>;
  user_id: string | null;
  workspace_id: string | null;
}

export interface DocumentCollaborators {
  created_at: Generated<Timestamp | null>;
  cursor_position: Json | null;
  document_id: string | null;
  id: Generated<string>;
  last_active: Timestamp | null;
  updated_at: Generated<Timestamp | null>;
  user_id: string | null;
}

export interface DocumentHistory {
  change_summary: string | null;
  content: Json | null;
  created_at: Generated<Timestamp | null>;
  document_id: string | null;
  id: Generated<string>;
  user_id: string | null;
  version: number | null;
}

export interface DocumentPermissions {
  channel_id: string | null;
  created_at: Generated<Timestamp | null>;
  document_id: string | null;
  id: Generated<string>;
  permission_level: string | null;
  updated_at: Generated<Timestamp | null>;
  user_id: string | null;
  workspace_id: string | null;
}

export interface Documents {
  content: Json | null;
  created_at: Generated<Timestamp | null>;
  created_by: string | null;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  is_archived: Generated<boolean | null>;
  is_favorite: Generated<boolean | null>;
  is_pinned: Generated<boolean | null>;
  is_template: Generated<boolean | null>;
  last_edited_by: string | null;
  parent_id: string | null;
  slug: string | null;
  title: string | null;
  updated_at: Generated<Timestamp | null>;
  version: Generated<number | null>;
  view_count: Generated<number | null>;
  workspace_id: string | null;
}

export interface FilePermissions {
  channel_id: string | null;
  created_at: Generated<Timestamp | null>;
  file_id: string | null;
  id: Generated<string>;
  permission_level: string | null;
  updated_at: Generated<Timestamp | null>;
  user_id: string | null;
  workspace_id: string | null;
}

export interface Files {
  channel_id: string | null;
  created_at: Generated<Timestamp | null>;
  deleted_at: Timestamp | null;
  description: string | null;
  document_id: string | null;
  download_count: Generated<number | null>;
  extension: string | null;
  file_path: string | null;
  file_size: Int8 | null;
  file_type: string | null;
  id: Generated<string>;
  is_public: Generated<boolean | null>;
  metadata: Json | null;
  mime_type: string | null;
  name: string | null;
  preview_available: Generated<boolean | null>;
  scan_status: string | null;
  thumbnail_url: string | null;
  updated_at: Generated<Timestamp | null>;
  uploaded_by: string | null;
  workspace_id: string | null;
}

export interface MeetingParticipants {
  created_at: Generated<Timestamp | null>;
  has_audio: Generated<boolean | null>;
  has_video: Generated<boolean | null>;
  id: Generated<string>;
  joined_at: Timestamp | null;
  left_at: Timestamp | null;
  meeting_id: string | null;
  role: string | null;
  status: string | null;
  updated_at: Generated<Timestamp | null>;
  user_id: string | null;
}

export interface Meetings {
  actual_end: Timestamp | null;
  actual_start: Timestamp | null;
  channel_id: string | null;
  created_at: Generated<Timestamp | null>;
  creator_id: string | null;
  deleted_at: Timestamp | null;
  description: string | null;
  external_meeting_id: string | null;
  id: Generated<string>;
  join_url: string | null;
  max_participants: number | null;
  meeting_provider: string | null;
  meeting_type: string | null;
  recording_available: Generated<boolean | null>;
  recording_url: string | null;
  recurrence_pattern: string | null;
  recurring: Generated<boolean | null>;
  scheduled_end: Timestamp | null;
  scheduled_start: Timestamp | null;
  status: string | null;
  title: string | null;
  updated_at: Generated<Timestamp | null>;
  workspace_id: string | null;
}

export interface MessageAttachments {
  created_at: Generated<Timestamp | null>;
  file_id: string | null;
  id: Generated<string>;
  message_id: string | null;
}

export interface MessageReactions {
  created_at: Generated<Timestamp | null>;
  emoji: string | null;
  id: Generated<string>;
  message_id: string | null;
  user_id: string | null;
}

export interface Messages {
  channel_id: string | null;
  content: string | null;
  created_at: Generated<Timestamp | null>;
  deleted_at: Timestamp | null;
  edited_at: Timestamp | null;
  has_attachments: Generated<boolean | null>;
  id: Generated<string>;
  is_edited: Generated<boolean | null>;
  is_pinned: Generated<boolean | null>;
  message_type: string | null;
  parent_id: string | null;
  pinned_at: Timestamp | null;
  pinned_by: string | null;
  reactions_count: Generated<number | null>;
  thread_reply_count: Generated<number | null>;
  updated_at: Generated<Timestamp | null>;
  user_id: string | null;
}

export interface Notifications {
  action_url: string | null;
  channel_id: string | null;
  content: string | null;
  created_at: Generated<Timestamp | null>;
  document_id: string | null;
  expires_at: Timestamp | null;
  id: Generated<string>;
  is_read: Generated<boolean | null>;
  meeting_id: string | null;
  message_id: string | null;
  sender_id: string | null;
  title: string | null;
  type: string | null;
  user_id: string | null;
  workspace_id: string | null;
}

export interface TaggableItems {
  created_at: Generated<Timestamp | null>;
  created_by: string | null;
  id: Generated<string>;
  tag_id: string | null;
  taggable_id: string | null;
  taggable_type: string | null;
}

export interface Tags {
  color: string | null;
  created_at: Generated<Timestamp | null>;
  created_by: string | null;
  id: Generated<string>;
  name: string | null;
  workspace_id: string | null;
}

export interface Users {
  avatar_url: string | null;
  bio: string | null;
  created_at: Generated<Timestamp | null>;
  date_of_birth: Timestamp | null;
  deleted_at: Timestamp | null;
  email: string;
  email_verified: Generated<boolean | null>;
  first_name: string | null;
  id: Generated<string>;
  is_admin: Generated<boolean | null>;
  last_active: Timestamp | null;
  last_name: string | null;
  locale: string | null;
  password_hash: string;
  phone: string | null;
  status: string | null;
  timezone: string | null;
  title: string | null;
  updated_at: Generated<Timestamp | null>;
  username: string;
}

export interface UserSessions {
  created_at: Generated<Timestamp | null>;
  device_info: Json | null;
  expires_at: Timestamp | null;
  id: Generated<string>;
  ip_address: string | null;
  is_active: Generated<boolean | null>;
  last_active: Timestamp | null;
  location: string | null;
  token: string | null;
  user_id: string | null;
}

export interface Webhooks {
  created_at: Generated<Timestamp | null>;
  created_by: string | null;
  events: Json | null;
  id: Generated<string>;
  is_active: Generated<boolean | null>;
  name: string | null;
  secret: string | null;
  updated_at: Generated<Timestamp | null>;
  url: string | null;
  workspace_id: string | null;
}

export interface WorkspaceMembers {
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  invited_by: string | null;
  is_favorite: Generated<boolean | null>;
  joined_at: Timestamp | null;
  notifications_enabled: Generated<boolean | null>;
  role: string | null;
  updated_at: Generated<Timestamp | null>;
  user_id: string | null;
  workspace_id: string | null;
}

export interface Workspaces {
  banner_url: string | null;
  country_code: string | null;
  created_at: Generated<Timestamp | null>;
  created_by: string | null;
  deleted_at: Timestamp | null;
  description: string | null;
  icon_url: string | null;
  id: Generated<string>;
  is_global: Generated<boolean | null>;
  is_national: Generated<boolean | null>;
  is_public: Generated<boolean | null>;
  max_members: number | null;
  name: string;
  slug: string;
  updated_at: Generated<Timestamp | null>;
}

export interface Database {
  audit_logs: AuditLogs;
  channel_members: ChannelMembers;
  channels: Channels;
  code_snippets: CodeSnippets;
  document_collaborators: DocumentCollaborators;
  document_history: DocumentHistory;
  document_permissions: DocumentPermissions;
  documents: Documents;
  file_permissions: FilePermissions;
  files: Files;
  meeting_participants: MeetingParticipants;
  meetings: Meetings;
  message_attachments: MessageAttachments;
  message_reactions: MessageReactions;
  messages: Messages;
  notifications: Notifications;
  taggable_items: TaggableItems;
  tags: Tags;
  user_sessions: UserSessions;
  users: Users;
  webhooks: Webhooks;
  workspace_members: WorkspaceMembers;
  workspaces: Workspaces;
}
